version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: myphpdockertest-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: myphpdockertest-nginx
    restart: always
    ports:
      - 8989:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
